Update pacman.yml

diff --git a/.github/workflows/pacman.yml b/.github/workflows/pacman.yml
--- a/.github/workflows/pacman.yml
+++ b/.github/workflows/pacman.yml
@@ -1,30 +1,50 @@
-name: Generate pacman animation
+name: Generate pacman Animation
 
 on:
-  schedule: # execute every 12 hours
-    - cron: "* */12 * * *"
-
+  schedule:
+    - cron: '0 */5 * * *'  # Every 12 hours at minute 0
   workflow_dispatch:
-
   push:
     branches:
-    - main
+      - main
 
 jobs:
   generate:
+    runs-on: ubuntu-latest
     permissions:
       contents: write
-    runs-on: ubuntu-latest
     timeout-minutes: 5
 
     steps:
-      - name: generate pacman-contribution-graph.svg
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Generate pacman-contribution-graph.svg
         uses: abozanona/pacman-contribution-graph@main
         with:
-          github_user_name: ${{ github.repository_owner }}
+          github_user_name: ergit24
 
+      - name: Debug file existence
+        run: |
+          ls -la
+          if [ -f pacman-contribution-graph.svg ]; then
+            echo "File exists"
+          else
+            echo "Error: pacman-contribution-graph.svg not found"
+            exit 1
+          fi
 
-      - name: push pacman-contribution-graph.svg to the output branch
+      - name: Setup output folder
+        run: |
+          mkdir -p dist
+          if [ -f pacman-contribution-graph.svg ]; then
+            mv pacman-contribution-graph.svg dist/
+          else
+            echo "Error: pacman-contribution-graph.svg not found"
+            exit 1
+          fi
+
+      - name: Push to output branch
         uses: crazy-max/ghaction-github-pages@v3.1.0
         with:
           target_branch: output
